### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by snej** [bendichter/tenseflow#10]
I'm trying to install this on macOS 10.14, but the mysqlclient dependency barfs during installation, presumably because MySQL isn't installed. 

It seems kind of odd for a text conversion tool to depend on MySQL! I assume this is some transitive dependency of the web UI. Would it be possible to publish a CLI-only version with fewer dependencies?

```
     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c2/sxm91vg53j1dyzpghmh3jt4h0000gn/T/pip-install-6dpn0in3/mysqlclient/setup.py'"'"'; __file__='"'"'/private/var/folders/c2/sxm91vg53j1dyzpghmh3jt4h0000gn/T/pip-install-6dpn0in3/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c2/sxm91vg53j1dyzpghmh3jt4h0000gn/T/pip-pip-egg-info-mpi6rwdh
         cwd: /private/var/folders/c2/sxm91vg53j1dyzpghmh3jt4h0000gn/T/pip-install-6dpn0in3/mysqlclient/
    Complete output (12 lines):
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c2/sxm91vg53j1dyzpghmh3jt4h0000gn/T/pip-install-6dpn0in3/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/private/var/folders/c2/sxm91vg53j1dyzpghmh3jt4h0000gn/T/pip-install-6dpn0in3/mysqlclient/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/c2/sxm91vg53j1dyzpghmh3jt4h0000gn/T/pip-install-6dpn0in3/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
```

**Comment by bendichter** [comment]
Agreed. The web app was a sort of learning experience. It would clearly be better to separate the app part from the backend, as most users would probably prefer a python or command line API
