### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by mirfan899** [bendichter/tenseflow#9]
I'm trying to run it for Python 3.6 and getting this error why try to run the given example.
```shell
from tenseflow import change_tense

change_tense('I will go to the store.', 'past')
```

Error:
```shell
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/irfan/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/201.7846.77/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/irfan/PycharmProjects/tenseflow/tenseflow/__init__.py", line 1, in <module>
    from .change_tense import *
  File "/home/irfan/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/201.7846.77/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/irfan/PycharmProjects/tenseflow/tenseflow/change_tense.py", line 3, in <module>
    from pattern.text.en import conjugate, PAST, PRESENT, SINGULAR, PLURAL
  File "/home/irfan/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/201.7846.77/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/irfan/PycharmProjects/tenseflow/.tense/lib/python3.6/site-packages/pattern/text/en/__init__.py", line 80, in <module>
    from pattern.text.en import wordnet
  File "/home/irfan/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/201.7846.77/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/irfan/PycharmProjects/tenseflow/.tense/lib/python3.6/site-packages/pattern/text/en/wordnet/__init__.py", line 57, in <module>
    nltk.data.find("corpora/" + token)
  File "/home/irfan/PycharmProjects/tenseflow/.tense/lib/python3.6/site-packages/nltk/data.py", line 557, in find
    return find(modified_name, paths)
  File "/home/irfan/PycharmProjects/tenseflow/.tense/lib/python3.6/site-packages/nltk/data.py", line 544, in find
    return ZipFilePathPointer(p, zipentry)
  File "/home/irfan/PycharmProjects/tenseflow/.tense/lib/python3.6/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/irfan/PycharmProjects/tenseflow/.tense/lib/python3.6/site-packages/nltk/data.py", line 396, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/home/irfan/PycharmProjects/tenseflow/.tense/lib/python3.6/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/irfan/PycharmProjects/tenseflow/.tense/lib/python3.6/site-packages/nltk/data.py", line 936, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

```

**Comment by mirfan899** [comment]
Okay, after googling I found the solution related to nltk packages.

https://github.com/clips/pattern/issues/252
